[package]
name = "cargo_project"
version = "0.1.0"
authors = ["Furkan Toprak <furkancemaltoprak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
